Form validate
tingamapuro04/Portfolio pull request #16
Opened 2022-05-19 15:43 UTC by tingamapuro04

I have worked on form_validate branch where i have a client side validation on the email input such that when a client will try to submit an email address that has an uppercase letter in in then the client will not be able to submit the form and instead will get an error message informing them that they should do it in lowercase instead. If that is implemented then the client will successfully submit the form.

2022-05-19 16:45 UTC, youmari requested changes
Hi @tingamapuro04  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ No linter error 
✔️ Great title and short summary 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 16:45 UTC, youmari commented on index.html
> +                    <input id="email_1" type="email" name="email" placeholder="natajayanj14@gmail.com" required>
- [ ] instead of putting your email in the `placeholder` attribute try to follow the Figma design and write something like `Enter your email`

2022-05-19 16:45 UTC, youmari commented on index.html
>                      <input type="text" name="name" placeholder="Merianne" maxlength="30" required>
instead of putting your name in the placeholder attribute try to follow the Figma design and write something like Enter your full name

2022-05-20 01:07 UTC, tingamapuro04 commented
In the form validate branch  i have added a more definitive placeholder as requested in the previous review.

2022-05-20 01:10 UTC, smunozmo approved these changes
Hi @tingamapuro04, 👋 

## Highlights 👏 

- Validation is working, great!
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 02:49 UTC, merged