Work
tingamapuro04/Portfolio pull request #2
Opened 2022-04-29 22:27 UTC by tingamapuro04

I am working on the work branch where i have introduced three more containers to the mobile skeleton. The first container describe my work and skills. In this container i have added four sub-sections with each sub-section having an image at the top and then followed by the body and then a button. I have used grid to place these four sub-sections.
In the second container I have introduced contains information about self generally . In the last container contains contact information and i have also included a form for user input.
I have continued to work the files such as index.html and nina.css

2022-04-29 23:27 UTC, tingamapuro04 commented
I have generally acted upon linter errors.

2022-04-30 01:00 UTC, koomekevo approved these changes
Hi @tingamapuro04 , 

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly implement the works section as suggested in the below screenshot

![tingacorrect](https://user-images.githubusercontent.com/87413774/166084335-28d2d412-523b-42cc-b190-9c2ab238ff48.png)

The below screenshot is your design

![tingaworksectionwrong](https://user-images.githubusercontent.com/87413774/166084358-2619131d-fb95-4109-ad5e-88925af620c2.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 01:08 UTC, koomekevo requested changes
Hi @tingamapuro04 , 

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly implement the works section as suggested in the below screenshot

![tingacorrect](https://user-images.githubusercontent.com/87413774/166084335-28d2d412-523b-42cc-b190-9c2ab238ff48.png)

The below screenshot is your design

![tingaworksectionwrong](https://user-images.githubusercontent.com/87413774/166084358-2619131d-fb95-4109-ad5e-88925af620c2.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 06:24 UTC, tingamapuro04 commented
I am working on the work branch where i have introduced three more containers to the mobile skeleton. The first container describe my work and skills. In this container i have added four sub-sections with each sub-section having an image at the top and then followed by the body and then a button. I have used grid to place these four sub-sections.
In the second container I have introduced contains information about self generally . In the last container contains contact information and i have also included a form for user input.
I have continued to work the files such as index.html and nina.css

I have added a wrap to the first and third cards in the class s-container.

2022-04-30 06:47 UTC, vic778 requested changes
## Hello @tingamapuro04 

Good job so far! I know you have worked hard on making this project.  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 06:47 UTC, vic778 commented on index.html
> +            </section>
`Figma template`
![Screenshot from 2022-04-30 09-42-37](https://user-images.githubusercontent.com/77842237/166095018-3d827650-a75e-44ed-b809-ccc4b8f19c15.png)
`your work`
![Screenshot from 2022-04-30 09-42-37](https://user-images.githubusercontent.com/77842237/166095091-b6adf0aa-166b-45dd-9dc3-44928888c0a9.png)

- [ ] Kindly You must stick to the design as much as possible (e.g., font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2022-04-30 09:31 UTC, tingamapuro04 commented
I am working on the work branch where i have introduced three more containers to the mobile skeleton. The first container describe my work and skills. In this container i have added four sub-sections with each sub-section having an image at the top and then followed by the body and then a button. I have used grid to place these four sub-sections.
In the second container I have introduced contains information about self generally . In the last container contains contact information and i have also included a form for user input.
I have continued to work the files such as index.html and nina.css

I have added a wrap to the first and third cards in the class s-container.

I have changed the font-sizes in the the class s-container.

2022-04-30 09:49 UTC, KDlamini approved these changes
### Hi @tingamapuro04 🙋‍♀️,  

Great work! 💯 
You have done a great job implementing the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

# Status: Approved ✔️ 

![giphyapproved](https://user-images.githubusercontent.com/38088818/166100633-bc087685-f7f7-4a97-bc86-e8f00e18c110.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 09:57 UTC, merged